---
deployments:
  giropops-senhas:
    name: "giropops-senhas-helm"
    image: "linuxtips/giropops-senhas:1.0"
    replicas: 3
    ports:
      - port: 5000
        targetPort: 5000
        name: "giropops-senhas-port"
        serviceType: "NodePort"
        nodePort: 32500
      - port: 8088
        targetPort: 8088
        name: "giropops-senhas-metrics"
        serviceType: "ClusterIP"
    labels:
      app: "giropops-senhas"
      env: "labs"
      live: "true"
    service:
      name: "giropops-senhas-svc"
      type: "ClusterIP"
      port: 5000
      targetPort: 5000
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  redis:
    name: "redis-helm"
    image: "redis"
    replicas: "1"
    labels:
      app: "redis"
      env: "labs"
      live: "true"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
services:
  giropops-senhas:
    labels:
      app: "giropops-senhas"
      env: "labs"
      live: "true"
    ports:
      - port: 5000
        targetPort: 5000
        name: "app"
        serviceType: "NodePort"
        nodePort: 32500
      - port: 8088
        targetPort: 8088
        name: "metrics"
        serviceType: "ClusterIP"
  redis:
    labels:
      app: "redis"
      env: "labs"
      live: "true"
    ports:
      - port: 6379
        targetPort: 6379
        name: "service"
        serviceType: "ClusterIP"
observability:
  giropops-senhas:
    logging: true
    metrics:
      enable: true
      path: "/metrics"
databases:
  giropops-senhas:
    mysql:
      host: "mysql.svc.cluster.local"
      port: 3306
      name: "MyDB"
